name: Elixir CD

on:
  release:
    types: [published]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  ELIXIR_VERSION: 1.17.3
  OTP_VERSION: 27.1.2

jobs:
    deploy:
    name: Deploy to Fly.io
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}